version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
    name: gitea

services:
  server:
    image: gitea/gitea:1.19.3 # Tip: dont skip versions when upgrading: https://dl.gitea.com/gitea/
    container_name: gitea
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
